# GitHub App Manifest for TrainMeX
# This file can be used to create a GitHub App programmatically
# See: https://docs.github.com/en/apps/creating-github-apps/setting-up-a-github-app/creating-a-github-app-from-a-manifest

name: TrainMeX
description: Hypnosis software for multi-screen video playback with independent settings
url: https://github.com/experiment-peepo/TrainMe
hook_attributes:
  url: https://your-webhook-url.com/webhook
  active: false
public: true
default_events:
  - release
  - push
default_permissions:
  contents: write
  metadata: read

